apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightreservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flightreservation
  template:
    metadata:
      labels:
        app: flightreservation
    spec:
      containers:
        - name: flightreservation
          image: ghcr.io/guy-ghis/flight:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/flightdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
