apiVersion: v1
kind: Service
metadata:
  name: flightreservation-service
spec:
  type: NodePort
  selector:
    app: flightreservation
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082
